"""LLM powered layout planning utilities."""
from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Dict, Iterable

from datapizza.clients.openai import OpenAIClient
from pydantic import BaseModel, Field

from .layouts import LayoutTemplate


class SlideLayoutDecision(BaseModel):
    """Single slide layout choice suggested by the LLM."""

    slide_number: int = Field(..., ge=1, description="Indice (1-based) della slide.")
    template: str = Field(..., description="Nome esatto del template da usare.")
    focus: str = Field(
        ..., description="Sintesi dell'idea/obiettivo di questa slide (max 10 parole)."
    )
    rationale: str = Field(
        ..., description="Perché questo template è il più adatto (max 30 parole)."
    )


class LayoutPlanProposal(BaseModel):
    """Structured response generated by the LLM with layout decisions."""

    plan_title: str = Field(..., description="Titolo sintetico del piano layout.")
    default_template: str = Field(..., description="Template più frequente da usare come default.")
    notes: str | None = Field(
        default=None,
        description="Annotazioni generali sul piano layout (opzionale).",
    )
    slides: list[SlideLayoutDecision] = Field(
        ..., description="Lista delle slide con template assegnato e rationale."
    )


@dataclass(frozen=True)
class LayoutPlanGeneratorConfig:
    api_key: str
    model_name: str
    temperature: float


class LayoutPlanGenerator:
    """Ask the LLM to pick the most suitable layout template per slide."""

    def __init__(self, config: LayoutPlanGeneratorConfig):
        self.client = OpenAIClient(
            api_key=config.api_key,
            model=config.model_name,
            system_prompt=(
                "Sei una presentation designer che decide la struttura del deck prima di creare le slide. "
                "Scegli i layout più efficaci basandoti sugli obiettivi comunicativi."
            ),
            temperature=config.temperature,
        )
        self._schema = json.dumps(LayoutPlanProposal.model_json_schema(), ensure_ascii=False)

    def generate(
        self,
        *,
        topic: str,
        requested_slides: int,
        template_options: Dict[str, LayoutTemplate],
    ) -> LayoutPlanProposal:
        if not template_options:
            raise ValueError("Nessun template disponibile per generare un layout.")

        prompt = self._build_prompt(topic, requested_slides, template_options.values())
        response = self.client.structured_response(
            input=prompt,
            output_cls=LayoutPlanProposal,
        )
        if not response.structured_data:
            raise RuntimeError("Il modello non ha proposto alcun layout.")
        proposal = response.structured_data[0]
        return proposal

    def _build_prompt(
        self,
        topic: str,
        requested_slides: int,
        templates: Iterable[LayoutTemplate],
    ) -> str:
        template_lines = []
        for template in sorted(templates, key=lambda tpl: tpl.name):
            block_types = ", ".join({block.type for block in template.blocks}) or "testo"
            desc = template.description or "N/A"
            template_lines.append(
                f"- {template.name}: {desc}. Blocchi principali: {block_types}."
            )

        template_section = "\n".join(template_lines)
        return (
            "Decidi la sequenza di layout per una presentazione Datapizza.\n"
            f"Brief della presentazione:\n{topic.strip()}\n\n"
            f"Numero totale di slide da pianificare: {requested_slides}.\n"
            "Puoi usare esclusivamente i template con questi nomi esatti:\n"
            f"{template_section}\n\n"
            "ISTRUZIONI\n"
            "- Assegna esattamente un template a ciascuna slide numerandole da 1 a N.\n"
            "- Usa sempre i nomi indicati (rispettando il case) per il campo template.\n"
            "- Imposta default_template con il layout più ricorrente.\n"
            "- Inserisci note opzionali per spiegare la logica complessiva.\n"
            "- Rispondi solo con JSON valido aderendo allo schema fornito.\n\n"
            f"SCHEMA JSON\n{self._schema}\n"
        )


def proposal_to_plan_data(
    *,
    proposal: LayoutPlanProposal,
    existing_templates: dict,
    requested_slides: int,
) -> dict:
    """Convert the LLM proposal into the JSON structure expected by layouts.json."""
    if not existing_templates:
        raise ValueError("Impossibile creare il layout: mancano i template di riferimento.")

    template_names = set(existing_templates.keys())
    default_template = proposal.default_template
    if default_template not in template_names:
        default_template = proposal.slides[0].template if proposal.slides else default_template
    if default_template not in template_names:
        default_template = next(iter(template_names))

    overrides: dict[str, str] = {}
    for slide in proposal.slides:
        slide_index = max(1, slide.slide_number)
        if slide_index > requested_slides:
            continue
        template_name = slide.template if slide.template in template_names else default_template
        if template_name != default_template:
            overrides[str(slide_index)] = template_name

    ordered_overrides = {idx: overrides[idx] for idx in sorted(overrides, key=lambda x: int(x))}

    plan_data = {
        "templates": existing_templates,
        "slide_plan": {
            "default": default_template,
            "overrides": ordered_overrides,
            "notes": proposal.notes,
            "plan_title": proposal.plan_title,
        },
    }
    return plan_data


def describe_proposal(proposal: LayoutPlanProposal) -> str:
    """Return a human-readable description of the LLM proposal."""
    lines = [f"Piano layout proposto: {proposal.plan_title}"]
    lines.append(f"Default template suggerito: {proposal.default_template}")
    if proposal.notes:
        lines.append(f"Note: {proposal.notes}")
    for slide in sorted(proposal.slides, key=lambda item: item.slide_number):
        lines.append(
            f"- Slide {slide.slide_number}: {slide.template} | Focus: {slide.focus} "
            f"(Motivo: {slide.rationale})"
        )
    return "\n".join(lines)
